name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Ensure conda env is activated in each step
        shell: bash -el {0}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up conda env
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment3.yml
          activate-environment: clipper3
          auto-activate-base: false
          channels: conda-forge,bioconda
          channel-priority: strict

      - name: Build and install (inc. pytest)
        run: pip install -e . pytest

      - name: Verify tool dependencies
        run: |
          samtools --version | head -1
          bedtools --version

      - name: Run tests
        run: pytest clipper/test -v
